import {
  Accessibility,
  Baby,
  Backpack,
  BatteryCharging,
  Bed,
  BedSingle,
  BellRing,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  ClipboardList,
  Coffee,
  DoorClosed,
  FileText,
  HeartHandshake,
  HeartPulse,
  Home,
  HousePlus,
  IdCard,
  Landmark,
  LockKeyhole,
  Mail,
  MessageCircleHeart,
  Monitor,
  Phone,
  Scale,
  ShieldCheck,
  Shirt,
  ShowerHead,
  Soup,
  Sparkles,
  Stethoscope,
  Toilet,
  Users,
  Wifi,
  WashingMachine,
  Sofa,
  HelpCircle
} from "lucide-react";

const iconMap = {
  accessibility: Accessibility,
  baby: Baby,
  backpack: Backpack,
  battery: BatteryCharging,
  bed: Bed,
  "bed-single": BedSingle,
  bell: BellRing,
  book: BookOpen,
  "case-legal": BriefcaseBusiness,
  bus: Bus,
  clipboard: ClipboardList,
  coffee: Coffee,
  "private-room": DoorClosed,
  document: FileText,
  "heart-hand": HeartHandshake,
  "heart-pulse": HeartPulse,
  home: Home,
  "housing-plus": HousePlus,
  "id-card": IdCard,
  legal: Scale,
  lockers: LockKeyhole,
  "public-office": Landmark,
  mail: Mail,
  "message-heart": MessageCircleHeart,
  monitor: Monitor,
  outreach: Users,
  phone: Phone,
  safety: ShieldCheck,
  shirt: Shirt,
  shower: ShowerHead,
  utensils: Soup,
  hygiene: Sparkles,
  stethoscope: Stethoscope,
  bathroom: Toilet,
  wifi: Wifi,
  laundry: WashingMachine,
  sofa: Sofa
};

export const ACTIVITY_ICON_OPTIONS = [
  { name: "shower", label: "Shower" },
  { name: "laundry", label: "Laundry" },
  { name: "utensils", label: "Meal" },
  { name: "shirt", label: "Clothing" },
  { name: "clipboard", label: "Case management" },
  { name: "case-legal", label: "Case + legal" },
  { name: "legal", label: "Legal support" },
  { name: "monitor", label: "Computer" },
  { name: "wifi", label: "Wi-Fi" },
  { name: "battery", label: "Phone charging" },
  { name: "phone", label: "Phone access" },
  { name: "mail", label: "Mail" },
  { name: "sofa", label: "Rest area" },
  { name: "bed", label: "Beds" },
  { name: "bed-single", label: "Single bed" },
  { name: "private-room", label: "Private room" },
  { name: "bathroom", label: "Bathroom" },
  { name: "heart-hand", label: "Support" },
  { name: "home", label: "Housing" },
  { name: "housing-plus", label: "Housing help" },
  { name: "stethoscope", label: "Health" },
  { name: "heart-pulse", label: "Mental health" },
  { name: "message-heart", label: "Counseling" },
  { name: "hygiene", label: "Hygiene" },
  { name: "outreach", label: "Outreach" },
  { name: "coffee", label: "Coffee" },
  { name: "id-card", label: "ID help" },
  { name: "document", label: "Documents" },
  { name: "bus", label: "Transportation" },
  { name: "baby", label: "Baby supplies" },
  { name: "accessibility", label: "Accessibility" },
  { name: "lockers", label: "Lockers" },
  { name: "backpack", label: "Storage" },
  { name: "book", label: "Learning" },
  { name: "public-office", label: "Public office" },
  { name: "safety", label: "Safety" },
  { name: "bell", label: "Reminder" }
];

export function ActivityIcon({ name, className = "" }) {
  const Icon = iconMap[name] || HelpCircle;
  return <Icon className={className} aria-hidden="true" />;
}
